project:
  name: @project.name@
  version: @project.version@
  artifactId: @project.artifactId@
  groupId: @project.groupId@

server:
  port: 1000
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: person
  jackson:
    default-property-inclusion: non_null
